name: ci

on: [push, pull_request]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          sudo apt-get update
          # sudo apt-get install -y libgl1-mesa-glx
          # sudo apt-get install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
          sudo apt-get install xvfb
          python3 -m pip install -r requirements.txt

      - name: test
        env:
          TEST: true
          QT_QPA_PLATFORM: offscreen
        # run: python main.py
        run: xvfb-run python main.py

      - name: pre-commit
        run: pre-commit run --all-files
